### ISSUE TITLE
能不能对smb路径增加金钱符共享支持？

### ISSUE THREAD

**Issue by jonathanhzs** [fanxiushu/xFsRedir#1]
\\xxx.xxx.xxx.xxx\共享$
这样的共享路径，对于可写共享，金钱符还是很必要的。

**Comment by fanxiushu** [comment]
没听说过\\Server\Path路径还能加 $ 的，我试了即使在资源管理器加$访问SMB也会失败。

**Comment by jonathanhzs** [comment]
是windows独有的，别的系统没有。
