### ISSUE TITLE
1366x768下添加目录界面无法选择最下面一行的设置

### ISSUE THREAD

**Issue by ssarrowcn** [fanxiushu/xFsRedir#12]
1366x768下添加目录界面无法选择最下面一行的设置

**Comment by fanxiushu** [comment]
软件是在 2560X1600和1080P分辨率的电脑环境中开发的，在较低分辨率下没怎么测试过，
再加上目录重定向的设置参数挺多，配置框拉的挺长。
作为临时变通办法，配置后，你可以按键盘的 “Enter”键，代表“设置”。

**Comment by ssarrowcn** [comment]
谢谢，我再测试下！
