### ISSUE TITLE
客户端能用命令行静默运行吗？想在pe环境中自动挂载

### ISSUE THREAD

**Issue by kkkgo** [fanxiushu/xFsRedir#2]
如题

**Comment by fanxiushu** [comment]
CSDN上好像有人提过同样的问题，xFsRedir不提供命令行参数，必须在界面中配置。
不过xFsRedir.ini配置文件可以手动配置，服务以 -server参数运行，
也许你多去折腾，能找到PE上静默运行的办法

**Comment by kkkgo** [comment]
xFsRedir.ini的是服务端吧？客户端支持ini配置吗？
