### ISSUE TITLE
使用SMB协议添加共享盘-大小识别问题

### ISSUE THREAD

**Issue by Lv-Ivan** [fanxiushu/xFsRedir#5]
你好，我使用SMB协议添加 如下共享 \\ip\pacs\htx 空间为26T可用 共60T
添加为本地E盘 显示499可用 共500GB
请问是设置问题还是BUG

**Comment by fanxiushu** [comment]
这不是BUG，因为
xFsRedir在生成新盘符时候，把虚拟磁盘大小固定设置为500GB, 
并且格式化为NTFS文件系统以保证最大兼容性，
并且把镜像文件保持到 \ProgramData\xFsRedir目录下，这个好像在CSDN的文章中已经阐述过了。

xFsRedir核心做的是目录到目录的映射，在一个盘符中可以同时做多个目录的映射的，
这种情况下磁盘容量是无法与真正远程服务端目录总大小联系起来的。因此就干脆简单固定500GB。
再说了，xFsRedir使用的filedisk这种简单的虚拟磁盘模式，无法与真正的windows磁盘匹敌，
有些软件还是会不认，
所以如果为了保证与本地文件系统几乎一致，需尽量把重定向目录设置到真正磁盘中。

**Comment by Lv-Ivan** [comment]
收到，大概理解您的意思了。感谢
